name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/docker-node .
      
      - name: Build the Docker Container
        run: docker run --name docker-node -p 81:3000 -d ${{ secrets.DOCKERHUB_USERNAME }}/docker-node

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/docker-node

      - name: Build the Docker Container REBUILD
        run: docker run --name docker-node -p 81:3000 -d ${{ secrets.DOCKERHUB_USERNAME }}/docker-node
