name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@dckr_pat_TDI5u87RLRyROevHnnn1b69jVYo
        with:
          username: scientechshub11
          password: dckr_pat_TDI5u87RLRyROevHnnn1b69jVYo

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag scientechshub11/docker-node

      - name: Docker Push
        run: docker push scientechshub11/docker-node