name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: |
          docker build -t scientechshub11/docker-node .
          docker login -u scientechshub11 -p dckr_pat_TDI5u87RLRyROevHnnn1b69jVYo
          docker tag scientechshub11/docker-node
          docker push scientechshub11/docker-node
