name: Build and Push Docker image to Docker Hub
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Scripts
        run: |
          docker build -t app .
          docker run --name docker-node -p 80:3000 -d scientechshub11/docker-node
          docker login -u scientechshub11 -p dckr_pat_TDI5u87RLRyROevHnnn1b69jVYo
          docker tag app scientechshub11/docker-node
          docker push scientechshub11/docker-node
          
